#!/usr/bin/env python3
"""Emit lib/otd-budget-data.ts from the budget sweeps.

    sport -> season -> playerId -> [listingCount, [cheapest rax-per-rating ...]]

Only the cheapest 20 rpr values are kept, which answers "does this card have
at least two listings at or under threshold T" exactly for any T — either the
count is under 20 (exact) or it is already >= 2 (all the filter asks).

budget_cache_deep.jsonl (the second pass) merges LAST, so its rows supersede the
first-pass rows for the cards it covers.

usage: export_otd_budget.py
env:   BUDGET_WORK
"""
import glob
import json
import os
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WORK = Path(os.environ.get("BUDGET_WORK", "/tmp"))

MAIN = sorted(glob.glob(str(WORK / "budget_cache_*.jsonl")))
MAIN = [c for c in MAIN if not c.endswith(".badcount") and not c.endswith("_deep.jsonl")]
DEEP = WORK / "budget_cache_deep.jsonl"
FILES = MAIN + ([str(DEEP)] if DEEP.exists() else [])

pool = json.loads((WORK / "budget_pool.json").read_text())

rows = {}       # (sport, season, pid) -> record (last write wins)
asof = {}       # sport -> latest file mtime contributing a record

for path in FILES:
    mt = os.path.getmtime(path)
    for line in open(path):
        if not line.strip():
            continue
        r = json.loads(line)
        rows[(r['sport'], r['season'], r['pid'])] = r
        asof[r['sport']] = max(asof.get(r['sport'], 0), mt)

data = {}
for (sport, season, pid), r in rows.items():
    data.setdefault(sport, {}).setdefault(str(season), {})[str(pid)] = [
        r['listings'], r['rpr']
    ]

stamp = lambda t: time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime(t))
counts = {}
for sport in sorted(data):
    n = sum(len(v) for v in data[sport].values())
    counts[sport] = {
        "pool": len(pool.get(sport, [])),
        "swept": n,
        "asof": stamp(asof.get(sport, time.time())),
    }

payload = json.dumps(data, separators=(',', ':'))
# Latest sweep across sports, not the export time — so re-exporting an unchanged
# cache set reproduces this file byte for byte (clean diffs on a refresh).
swept_at = stamp(max(asof.values())) if asof else stamp(time.time())
out = f'''/** Generated by scripts/budget/export_otd_budget.py — do not hand-edit.
 *
 * Live marketplace depth per card, used by the Budget filter: how many listings
 * a card has right now, and its cheapest rax-per-rating values (rax price /
 * the card's own rating).
 *
 *   sport -> season -> playerId -> [listingCount, [rpr, ...]]
 *
 * Only the cheapest 20 rpr values are stored, which answers "does this card
 * have at least two listings at or under threshold T" exactly for any T.
 *
 * The pool is bounded by cost: 7 marketplace calls per card is ~13h for all
 * 8,441 cards, and listings expire within hours, so each sport is swept over
 * its top 80 cards by OTD value UNION its top 40 by best single claim day.
 * Sports not present here are dropped from a budget solve rather than guessed.
 *
 * A snapshot, not a feed — the UI reports the sweep time per sport.
 * See scripts/budget/README.md to re-sweep.
 */
export const OTD_BUDGET_ASOF = "{swept_at}";

export const OTD_BUDGET_META: Record<string, {{ pool: number; swept: number; asof: string }}> =
  {json.dumps(counts, separators=(',', ':'))};

export const OTD_BUDGET_DATA =
  '{payload}';
'''
dst = REPO / "lib" / "otd-budget-data.ts"
dst.write_text(out)
print("wrote", dst, len(out), "bytes")
for s, c in counts.items():
    print(f"  {s:6} pool={c['pool']:4} swept={c['swept']:4} asof={c['asof']}")
