/** Generated by scripts/budget/export_budget_searches.py — do not hand-edit.
 *
 * The Optimal Budget search presets shown in Walkr's Menu. Each preset's players
 * come from the best 5-card On-This-Day lineup at the budget ceiling
 * (10 rax/rating, >= 2 live listings) — the same rule and the same data the
 * Optimal OTD panel uses, so the two can't drift. Re-run the generator after a
 * sweep.
 *
 * Grouped per sport into {sport, season} slices because a marketplace query is
 * always one sport/season; "All Sports" is every sport's lineup at once.
 *
 * A preset may also carry `playerCaps`: per-player rax-per-rating ceilings for
 * cards the lineup buys looser than the ceiling on purpose (deep market => you
 * can level them to Legendary fast). Everyone else in the lineup screens at the
 * ceiling. Keep both in sync by re-running the generator.
 */
import type { WalkerOtdSlice } from "./deals";

export interface BudgetSearchPreset {
  id: string;
  label: string;
  /** How many players the preset searches for. */
  cards: number;
  /** Base rax/yr the lineup is worth (unboosted). */
  best: number;
  /** Per-player ceilings, for cards bought above BUDGET_SEARCH_CEILING. */
  playerCaps?: Record<string, number>;
  slices: WalkerOtdSlice[];
}

/** Ceiling the lineups were solved at, in rax per rating point. */
export const BUDGET_SEARCH_CEILING = 10;

/** Rating factor the quick searches run at — the Low PerRax screen. */
export const BUDGET_SEARCH_FACTOR = 11;

export const BUDGET_SEARCH_PRESETS: BudgetSearchPreset[] = [
  {
    id: "nba",
    label: "NBA",
    cards: 5,
    best: 1680,
    slices: [{"sport": "nba","season": 2026,"players": ["De'Aaron Fox","James Harden"]},{"sport": "nba","season": 2025,"players": ["Pascal Siakam"]},{"sport": "nba","season": 2024,"players": ["Pascal Siakam","Kyrie Irving"]}],
  },
  {
    id: "nhl",
    label: "NHL",
    cards: 7,
    best: 2368,
    playerCaps: {"Jack Eichel": 15, "Filip Forsberg": 15},
    slices: [{"sport": "nhl","season": 2025,"players": ["Matt Boldy","Mitch Marner","Jack Eichel"]},{"sport": "nhl","season": 2024,"players": ["Sam Bennett","Kyle Connor"]},{"sport": "nhl","season": 2023,"players": ["Stuart Skinner","Filip Forsberg"]}],
  },
  {
    id: "ncaam",
    label: "CBB",
    cards: 5,
    best: 1437,
    slices: [{"sport": "ncaam","season": 2026,"players": ["Juke Harris","Chris Bell","Rob Martin"]},{"sport": "ncaam","season": 2024,"players": ["Al-Amir Dawes","Ben Krikke"]}],
  },
  {
    id: "mlb",
    label: "MLB",
    cards: 5,
    best: 1838,
    slices: [{"sport": "mlb","season": 2026,"players": ["Fernando Tatis Jr.","Kyle Schwarber","CJ Abrams"]},{"sport": "mlb","season": 2025,"players": ["Vladimir Guerrero Jr."]},{"sport": "mlb","season": 2024,"players": ["Pete Alonso"]}],
  },
  {
    id: "wnba",
    label: "WNBA",
    cards: 5,
    best: 1787,
    slices: [{"sport": "wnba","season": 2026,"players": ["Kelsey Mitchell","Paige Bueckers"]},{"sport": "wnba","season": 2025,"players": ["Chelsea Gray","Satou Sabally"]},{"sport": "wnba","season": 2024,"players": ["Kayla McBride"]}],
  },
  {
    id: "all",
    label: "All Sports",
    cards: 27,
    best: 9110,
    playerCaps: {"Jack Eichel": 15, "Filip Forsberg": 15},
    slices: [{"sport": "nba","season": 2026,"players": ["De'Aaron Fox","James Harden"]},{"sport": "nba","season": 2025,"players": ["Pascal Siakam"]},{"sport": "nba","season": 2024,"players": ["Pascal Siakam","Kyrie Irving"]},{"sport": "nhl","season": 2025,"players": ["Matt Boldy","Mitch Marner","Jack Eichel"]},{"sport": "nhl","season": 2024,"players": ["Sam Bennett","Kyle Connor"]},{"sport": "nhl","season": 2023,"players": ["Stuart Skinner","Filip Forsberg"]},{"sport": "ncaam","season": 2026,"players": ["Juke Harris","Chris Bell","Rob Martin"]},{"sport": "ncaam","season": 2024,"players": ["Al-Amir Dawes","Ben Krikke"]},{"sport": "mlb","season": 2026,"players": ["Fernando Tatis Jr.","Kyle Schwarber","CJ Abrams"]},{"sport": "mlb","season": 2025,"players": ["Vladimir Guerrero Jr."]},{"sport": "mlb","season": 2024,"players": ["Pete Alonso"]},{"sport": "wnba","season": 2026,"players": ["Kelsey Mitchell","Paige Bueckers"]},{"sport": "wnba","season": 2025,"players": ["Chelsea Gray","Satou Sabally"]},{"sport": "wnba","season": 2024,"players": ["Kayla McBride"]}],
  },
];
